In [1]:
import pandas as pd
var = pd.read_csv("//Users//dhruvmehta//Developer//code//DS-AI-ML-GEN-AI//python//Data_analysis//dropna_practice.csv")
var
# python/Data_analysis/pandas.ipynb
# /Users/dhruvmehta/Developer/code/DS-AI-ML-GEN-AI/python/Data_analysis/pandas.ipynb

     Name   Age       City   Salary Department
0   Aarav  22.0       Pune  45000.0         IT
1    Diya   NaN     Mumbai  52000.0         HR
2   Rohan  25.0        NaN      NaN         IT
3  Ananya  24.0      Delhi  60000.0        NaN
4   Kabir   NaN       Pune  48000.0    Finance
5   Meera  27.0        NaN      NaN         HR
6   Arjun  23.0  Bangalore  55000.0        NaN
7  Ishita   NaN      Delhi  62000.0         IT
8  Vivaan  26.0     Mumbai      NaN    Finance
9    Sara  28.0        NaN  70000.0         HR

In [4]:
var.dropna(axis=0)

    Name   Age  City   Salary Department
0  Aarav  22.0  Pune  45000.0         IT

In [5]:
var.dropna(axis=1)

     Name
0   Aarav
1    Diya
2   Rohan
3  Ananya
4   Kabir
5   Meera
6   Arjun
7  Ishita
8  Vivaan
9    Sara

In [6]:
var.dropna(how="any")

    Name   Age  City   Salary Department
0  Aarav  22.0  Pune  45000.0         IT

In [7]:
var.dropna(how="all")

     Name   Age       City   Salary Department
0   Aarav  22.0       Pune  45000.0         IT
1    Diya   NaN     Mumbai  52000.0         HR
2   Rohan  25.0        NaN      NaN         IT
3  Ananya  24.0      Delhi  60000.0        NaN
4   Kabir   NaN       Pune  48000.0    Finance
5   Meera  27.0        NaN      NaN         HR
6   Arjun  23.0  Bangalore  55000.0        NaN
7  Ishita   NaN      Delhi  62000.0         IT
8  Vivaan  26.0     Mumbai      NaN    Finance
9    Sara  28.0        NaN  70000.0         HR

In [11]:
var.dropna(subset=["Salary"])

     Name   Age       City   Salary Department
0   Aarav  22.0       Pune  45000.0         IT
1    Diya   NaN     Mumbai  52000.0         HR
3  Ananya  24.0      Delhi  60000.0        NaN
4   Kabir   NaN       Pune  48000.0    Finance
6   Arjun  23.0  Bangalore  55000.0        NaN
7  Ishita   NaN      Delhi  62000.0         IT
9    Sara  28.0        NaN  70000.0         HR

In [12]:
var.dropna(inplace=True)
var

    Name   Age  City   Salary Department
0  Aarav  22.0  Pune  45000.0         IT

In [15]:
var.fillna("python")
# var

    Name   Age  City   Salary Department
0  Aarav  22.0  Pune  45000.0         IT

In [16]:
import pandas as pd
var = pd.read_csv("//Users//dhruvmehta//Developer//code//DS-AI-ML-GEN-AI//python//Data_analysis//dropna_practice.csv")
var
# python/Data_analysis/pandas.ipynb
# /Users/dhruvmehta/Developer/code/DS-AI-ML-GEN-AI/python/Data_analysis/pandas.ipynb

     Name   Age       City   Salary Department
0   Aarav  22.0       Pune  45000.0         IT
1    Diya   NaN     Mumbai  52000.0         HR
2   Rohan  25.0        NaN      NaN         IT
3  Ananya  24.0      Delhi  60000.0        NaN
4   Kabir   NaN       Pune  48000.0    Finance
5   Meera  27.0        NaN      NaN         HR
6   Arjun  23.0  Bangalore  55000.0        NaN
7  Ishita   NaN      Delhi  62000.0         IT
8  Vivaan  26.0     Mumbai      NaN    Finance
9    Sara  28.0        NaN  70000.0         HR

In [17]:
var.fillna("python")
# var

     Name     Age       City   Salary Department
0   Aarav    22.0       Pune  45000.0         IT
1    Diya  python     Mumbai  52000.0         HR
2   Rohan    25.0     python   python         IT
3  Ananya    24.0      Delhi  60000.0     python
4   Kabir  python       Pune  48000.0    Finance
5   Meera    27.0     python   python         HR
6   Arjun    23.0  Bangalore  55000.0     python
7  Ishita  python      Delhi  62000.0         IT
8  Vivaan    26.0     Mumbai   python    Finance
9    Sara    28.0     python  70000.0         HR

In [18]:
var.fillna(method="ffill")

/var/folders/cv/l3657x1n7lqgp1htnnylt9_80000gn/T/ipykernel_33948/3062787689.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  var.fillna(method="ffill")

     Name   Age       City   Salary Department
0   Aarav  22.0       Pune  45000.0         IT
1    Diya  22.0     Mumbai  52000.0         HR
2   Rohan  25.0     Mumbai  52000.0         IT
3  Ananya  24.0      Delhi  60000.0         IT
4   Kabir  24.0       Pune  48000.0    Finance
5   Meera  27.0       Pune  48000.0         HR
6   Arjun  23.0  Bangalore  55000.0         HR
7  Ishita  23.0      Delhi  62000.0         IT
8  Vivaan  26.0     Mumbai  62000.0    Finance
9    Sara  28.0     Mumbai  70000.0         HR

In [21]:
var.replace(to_replace=25, value=1)

     Name   Age       City   Salary Department
0   Aarav  22.0       Pune  45000.0         IT
1    Diya   NaN     Mumbai  52000.0         HR
2   Rohan   1.0        NaN      NaN         IT
3  Ananya  24.0      Delhi  60000.0        NaN
4   Kabir   NaN       Pune  48000.0    Finance
5   Meera  27.0        NaN      NaN         HR
6   Arjun  23.0  Bangalore  55000.0        NaN
7  Ishita   NaN      Delhi  62000.0         IT
8  Vivaan  26.0     Mumbai      NaN    Finance
9    Sara  28.0        NaN  70000.0         HR

In [22]:
sr1 = pd.Series([1,2,3,4])
sr2 = pd.Series([11,21,31,41])
pd.concat([sr1, sr2])

0     1
1     2
2     3
3     4
0    11
1    21
2    31
3    41
dtype: int64

In [ ]:
import pandas as pd

var = pd.DataFrame()